# Generated by Django 4.2.5 on 2023-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('editorial', models.CharField(max_length=50)),
            ],
        ),
    ]
