# Generated by Django 4.2.5 on 2023-10-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
        ('Libros', '0002_alter_libro_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Areas.area'),
        ),
    ]
